REPLACE  INTO  SYS_USER_GROUP(SID,DESCRIPTION,GROUP_NAME,DISPLAY_NAME,PARENT_ID) VALUES(1,"Group of Administrators","Administrators","Administrators",0);
REPLACE  INTO  SYS_USER(SID,EMAIL,PASSWORD,USER_NAME,FIRST_NAME,LAST_NAME,DATE_CREATED,DATE_MODIFIED,IS_ACTIVE,IS_EXPIRED,GENDER,IMG) VALUES(1,"admin@netsync.com","{bcrypt}$2a$10$cS8yzuSFOvcWX.IJ1ZrHWePm2vIjM8R4TqmnynNmY8eOqnyK1IQIS","admin","STEVE","WANG",NOW(),NOW(),1,1,1,"/assets/img/male.jpg");
REPLACE  INTO  SYS_ROLE(SID,DESCRIPTION,ROLE_NAME,DISPLAY_NAME) VALUES(1,"Role of Administrator","ADMIN","ADMIN");

REPLACE  INTO  SYS_MENU(SID,DESCRIPTION,MENU_NAME,MENU_GROUP_ID,URL,DISPLAY_NAME,IS_ACTIVE,DATE_CREATED,DATE_MODIFIED) VALUES(1,"Group Settings","group",1,"/sencwork/sys/group","Group Settings",1,NOW(),NOW());
REPLACE  INTO  SYS_MENU(SID,DESCRIPTION,MENU_NAME,MENU_GROUP_ID,URL,DISPLAY_NAME,IS_ACTIVE,DATE_CREATED,DATE_MODIFIED) VALUES(2,"User Settings","user",1,"/sencwork/sys/user","User Settings",1,NOW(),NOW());
REPLACE  INTO  SYS_MENU(SID,DESCRIPTION,MENU_NAME,MENU_GROUP_ID,URL,DISPLAY_NAME,IS_ACTIVE,DATE_CREATED,DATE_MODIFIED) VALUES(3,"Menu Settings","menu",1,"/sencwork/sys/menu","Menu Settings",1,NOW(),NOW());
REPLACE  INTO  SYS_MENU(SID,DESCRIPTION,MENU_NAME,MENU_GROUP_ID,URL,DISPLAY_NAME,IS_ACTIVE,DATE_CREATED,DATE_MODIFIED) VALUES(4,"Role Settings","role",1,"/sencwork/sys/role","Role Settings",1,NOW(),NOW());

REPLACE  INTO  SYS_MENU(SID,DESCRIPTION,MENU_NAME,MENU_GROUP_ID,URL,DISPLAY_NAME,IS_ACTIVE,DATE_CREATED,DATE_MODIFIED) VALUES(5,"Query Orders","Query Order",2,"/sencwork/omm/orderQuery","Query Order",1,NOW(),NOW());
REPLACE  INTO  SYS_MENU(SID,DESCRIPTION,MENU_NAME,MENU_GROUP_ID,URL,DISPLAY_NAME,IS_ACTIVE,DATE_CREATED,DATE_MODIFIED) VALUES(6,"Order Statistic","Order Report",2,"/sencwork/omm/orderReport","Order Statistic",1,NOW(),NOW());
REPLACE  INTO  SYS_MENU(SID,DESCRIPTION,MENU_NAME,MENU_GROUP_ID,URL,DISPLAY_NAME,IS_ACTIVE,DATE_CREATED,DATE_MODIFIED) VALUES(7,"third level","Create Order",2,"/sencwork/omm/orderReport","Create Order",1,NOW(),NOW());

REPLACE  INTO  SYS_MENU_GROUP(SID,DESCRIPTION,NAME,PARENT_ID,IS_ROOT) VALUES(1,"Administration","Administration",0,true);
REPLACE  INTO  SYS_MENU_GROUP(SID,DESCRIPTION,NAME,PARENT_ID,IS_ROOT) VALUES(2,"Order Management","Order Management",0,true);

REPLACE  INTO  SYS_JOIN_USER_GROUP(USER_SID,GROUP_SID) VALUES(1,1);
REPLACE  INTO  SYS_JOIN_USER_ROLE(USER_SID,ROLE_SID) VALUES(1,1);

REPLACE  INTO  SYS_JOIN_ROLE_MENU(ROLE_SID,MENU_SID) VALUES(1,1);
REPLACE  INTO  SYS_JOIN_ROLE_MENU(ROLE_SID,MENU_SID) VALUES(1,2);
REPLACE  INTO  SYS_JOIN_ROLE_MENU(ROLE_SID,MENU_SID) VALUES(1,3);
REPLACE  INTO  SYS_JOIN_ROLE_MENU(ROLE_SID,MENU_SID) VALUES(1,4);
REPLACE  INTO  SYS_JOIN_ROLE_MENU(ROLE_SID,MENU_SID) VALUES(1,5);
REPLACE  INTO  SYS_JOIN_ROLE_MENU(ROLE_SID,MENU_SID) VALUES(1,6);